name: GitHub pages

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '8.x'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 1

      - name: Use Node.JS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build GitHub Pages
        run: |
          npm install
          npm run build
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: gh-pages
          publish_dir: ./_book
          force_orphan: true
